project:
  type: website
  output-dir: docs

website:
  title: "SVS QIC: QI Toolkit"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - data-vis.qmd
      - cs-readmit.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

