project:
  type: website

website:
  title: "SVS QIC: QI Toolkit"
  navbar:
    left:
      - href: qic-data.qmd
        text: Home
      - cs-readmit.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

